import { Montserrat, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { } from "module";
import { HeroThemeProviders } from "./providers/HeroThemeProviders";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";



export const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700', '800'], // আপনার প্রয়োজন অনুযায়ী ওয়েট নিতে পারেন
  variable: '--font-montserrat', // Tailwind-এ ব্যবহারের জন্য ভ্যারিয়েবল নাম
});


const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-jakarta', // Tailwind-এ ব্যবহারের জন্য ভ্যারিয়েবল নাম
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-theme="light"
      className={`h-full antialiased `}
    >

      <body className={`${plusJakartaSans.className}  min-h-full flex flex-col`} >
        <HeroThemeProviders>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </HeroThemeProviders>
      </body>
    </html>
  );
}

