import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { } from "module";
import { HeroThemeProviders } from "./providers/HeroThemeProviders";
import Navbar from "@/components/shared/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >

      <body className="min-h-full flex flex-col">
        <HeroThemeProviders>
          <Navbar />
          {children}
        </HeroThemeProviders>
      </body>
    </html>
  );
}
